### ISSUE TITLE
npm install @types/rethinkdb installs type definitions for rethinkdb 1.10.0

### ISSUE THREAD

**Issue by tmkn** [types/npm-rethinkdb#3]
When I run the above command I get type definitions for rethinkdb 1.10.0 apparently from here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/rethinkdb

This repository however contains type definitions for 2.3.0 which I need but it doesn't seem to be published to npm yet?

**Comment by unional** [comment]
To install this, you need `typings install -S npm~rethinkdb`

**Comment by niieani** [comment]
Or without typings, `npm install github:types/npm-rethinkdb`.

**Comment by blakeembrey** [comment]
To further clarify, we can not publish to NPM. TypeScript owns that process, I've done as much possible to make it work for users (including enabling the `npm install` from GitHub @niieani mentioned). See https://github.com/Microsoft/types-publisher/issues/4 for more information.

**Comment by niieani** [comment]
We could PR to DefinitelyTyped, which gets autopublished to `@types/...`. Maybe it's worth waiting until we iron out more bugs, maybe not, since the old typings which are there are pretty useless anyway.

**Comment by blakeembrey** [comment]
I don't really have any desire to keep PRing DefinitelyTyped though. It's just a duplication of source code and effort, which sucks. If I were to do it here, I'd have to consider the workflow with the other 100 modules under @types, and it just doesn't scale. Not even in terms of code, copying and pasting is terrible but doable, but in terms of maintenance. Unless you decide to subscribe to DefinitelyTyped issues (of which, 99.9% won't be relevant to you) you'll never know if someone run into an issue or has submitted a fix. It's not really even possible to have project discussions on there, like the ones you've already created, because there's just _too many_ projects there to focus.

**Comment by niieani** [comment]
Yeah, that's the downside. Perhaps there could be a bot for @types which PRs all changes from its repos to DefinitelyTyped automatically? It's a really sad state to have two sources of typings rather than just one, "canonical" one. Maybe we could work this out together with the TypeScript team?

**Comment by blakeembrey** [comment]
See the issue I linked to for the proposed solution to this, I did have this discussion with them three months ago when they started with the `node_modules/@types`, it's just they've been busy with everything else and the interop wasn't a priority.

**Comment by niieani** [comment]
Aah, cool. Good to hear 👍
